### ISSUE TITLE
check attribute names in lib/conllu.py

### ISSUE THREAD

**Issue by chiarcos** [hectormartinez/ud_unsup_parser#1]
I was trying to use that as baseline for parsing unseen UD languages. I got the following trace, and either the error message is misleading or there is a naming issue.

I ran `$PYTHON $UDP/udup.py --steps headrule --input $TEST --posrules $UDP/../data/posrules.tsv --output $OUTPUT`

With  `$UDP` pointing to the `src` directory and `$PYTHON=python3`. Input is an Old Saxon file in CoNLL-U format (the usual 10 cols, sentence breaks, no comments, no metadata, ID, FORM, LEMMA, UPOS, XPOS, HEAD and DEP specified, everything else `_`).

	Traceback (most recent call last):
	  File "./ud_unsup_parser/src/udup.py", line 631, in <module>
	    main()
	  File "./ud_unsup_parser/src/udup.py", line 573, in main
	    orig_treebank = cio.read_conll_u(args.input)
	  File "/cygdrive/c/Users/chiarcos/Desktop/corpus/heliand/parsing/baseline/ud_unsup_parser/src/lib/conll.py", line 448, in read_conll_u
	    sent.node[token_dict['id']].update({k: v for (k, v) in token_dict.items()
	AttributeError: 'DependencyTree' object has no attribute 'node'

Data snippet (original separators are `\t`):

	1       Manega  manag   ADJ     Q^N^PL  _       0       root    _       _
	2       uuaron  wesan   AUX     BEDI^3^PL       _       1       aux     _       _
	3       the     the     SCONJ   C       _       7       mark    _       _
	4       sia     he      PRON    PRO^PL^A^3      _       7       nsubj   _       _
	5       iro     his     DET     PRO$^SG^3^N     _       6       det     _       _
	6       mod     mod     NOUN    N^N^SG  _       7       obj     _       _
	7       gespon  spanan  VERB    GE+VBDI^SG^3    _       1       acl     _       _

**Comment by hectormartinez** [comment]
Hi Christian, sorry about the inconvenience!
First of all, thanks for showing interest in this work.

As very often with these things, I have not revisited the code since I
transitioned to industry.

The DependencyTree class inherits from NetworkX.DiGraph, which at the time
the code was developed (networkx==2.1) had a property called *node[]*
In later versions (from 2.4
<https://networkx.org/documentation/stable/release/release_2.4.html>) they
renamed it to *nodes* which makes more sense, but the change broke
backwards compatibility.
You can downgrade your version of networkx to 2.1 and then the property
will be accessible -- not great, I know.
I would like to update the code to the latest version of networkx but I am fairly out of capacity for the next
couple of weeks.
Let me know if that does the trick!

**Comment by hectormartinez** [comment]
i've updated the code for networkx==2.4, from the input example I get

```
1	Manegb	manag	ADJ	Q^N^PL	rank:6	6	root	_	_
2	uuaron	wesan	AUX	BEDI^3^PL	rank:5	7	root	_	_
3	the	the	SCONJ	C	rank:2	7	root	_	_
4	sia	he	PRON	PRO^PL^A^3	rank:3	7	root	_	_
5	iro	his	DET	PRO$^SG^3^N	rank:4	6	root	_	_
6	mod	mod	NOUN	N^N^SG	rank:1	7	root	_	_
7	gespon	spanan	VERB	GE+VBDI^SG^3	rank:0	0	root	_	_
```


Note that "rank:0" is internal logging showing the PageRank of each token in the sentence, saved in the FEATS column

**Comment by chiarcos** [comment]
Thank you, that solved it ;)
